### ISSUE TITLE
Function and view module import error

### ISSUE THREAD

**Issue by intisarnaheen** [jjrodcast/SocialDistanceDetector#1]
I am trying to import the functions and view modules. But an error message is shown for this.
![issue](https://user-images.githubusercontent.com/35806906/87339815-f7082c00-c568-11ea-86c2-42cfd14de3c5.png)

**Comment by jjrodcast** [comment]
@intisarnaheen
I will check the error, are you using colab o local jupyter notebook? .
Please reset your kernel and run it again.
If the error persists comment here with a "Still error importing utils from view"

**Comment by intisarnaheen** [comment]
I used colab. I don't see any error anymore. Thanks

**Comment by jjrodcast** [comment]
@intisarnaheen you are welcome

**Comment by jjrodcast** [comment]
No issue detected
